"""Export results to markdown, CSV and Excel."""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd

from .. import __version__
from ..validate import report as validation_report
from ..validate import verification_status
from .tables import (candidate_table, comparison_to_benchmarks,
                     limitations_table, pareto_table, provenance_table,
                     targets_table)

HEADER = """# Low-E coating screening results

Generated by pvdlowe {version} on {today}.

**Read this first.** Every performance number below is a *model* output, not a
measurement. The optical constants come from published Lorentz-Drude fits with
free-electron damping re-anchored to DC resistivity; the thin-film resistivity
comes from a Fuchs-Sondheimer and Mayadas-Shatzkes size-effect model whose
specularity and grain-boundary parameters are fitted, not derived; the
percolation thresholds are calibrated to two literature values that have not
themselves been checked against their primary sources. The framework is a tool
for ranking candidates and designing experiments. It is not a substitute for
depositing the films.

{verification}
"""


def _md(df: pd.DataFrame) -> str:
    if df is None or df.empty:
        return "_(no rows)_\n"
    try:
        return df.to_markdown(index=False) + "\n"
    except ImportError:
        return "```\n" + df.to_string(index=False) + "\n```\n"


def markdown_report(path: Path | None = None) -> str:
    """Full results report as markdown."""
    status = verification_status()
    parts = [HEADER.format(version=__version__, today=date.today().isoformat(),
                           verification=status["message"])]

    parts += ["\n## Specification and weighting\n", _md(targets_table()),
              "\nThe weighting is from the brief's section 14. Note that "
              "emissivity and sheet resistance are both governed by the same "
              "free-carrier response, so their weights are not independent; "
              "see the scoring diagnostics.\n"]

    parts += ["\n## Candidate results\n", _md(candidate_table())]

    cmp_df = comparison_to_benchmarks()
    if not cmp_df.empty:
        parts += ["\n## Against the silver benchmark\n", _md(cmp_df),
                  "\nPositive silver and cost savings with small negative "
                  "performance changes are the combinations worth taking to "
                  "the sputter tool.\n"]

    parts += ["\n## Pareto front\n", _md(pareto_table()),
              "\nThese are the candidates not dominated on transmittance, "
              "emissivity and cost simultaneously. Anything absent from this "
              "table is beaten on every one of those axes by something in it.\n"]

    parts += ["\n## Evidence grade\n", _md(provenance_table()),
              "\nRows marked as hypotheses have no measured or calculated "
              "properties for that exact composition. Their scores are "
              "extrapolations and should not enter a thesis table as results.\n"]

    parts += ["\n## What this framework does not predict\n",
              _md(limitations_table())]

    parts += ["\n## Model validation\n", "```\n", validation_report(), "\n```\n"]

    text = "".join(parts)
    if path:
        Path(path).write_text(text)
    return text


def to_excel(path: Path, include_sweeps: bool = False) -> Path:
    """Write every table to a multi-sheet workbook."""
    path = Path(path)
    sheets = {
        "Candidates": candidate_table(),
        "vs Benchmark": comparison_to_benchmarks(),
        "Pareto": pareto_table(),
        "Targets": targets_table(),
        "Provenance": provenance_table(),
        "Not predicted": limitations_table(),
    }
    if include_sweeps:
        from ..optimize.sweep import microstructure_comparison, thickness_sweep
        sheets["Ag thickness sweep"] = thickness_sweep("Ag")
        sheets["Microstructure"] = microstructure_comparison()
    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        for name, df in sheets.items():
            if df is not None and not df.empty:
                df.to_excel(writer, sheet_name=name[:31], index=False)
    return path


def to_csv_directory(directory: Path) -> Path:
    """Write every table as a separate CSV."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    tables = {"candidates": candidate_table(),
              "vs_benchmark": comparison_to_benchmarks(),
              "pareto": pareto_table(), "targets": targets_table(),
              "provenance": provenance_table(),
              "not_predicted": limitations_table()}
    for name, df in tables.items():
        if df is not None and not df.empty:
            df.to_csv(directory / f"{name}.csv", index=False)
    return directory


__all__ = ["markdown_report", "to_excel", "to_csv_directory"]
